export default {
    START_API:"START_API",
    END_API:"END_API",
    OPEN_MODAL:"OPEN_MODAL",
    CLOSE_MODAL:"CLOSE_MODAL",

    SUCCESS_LOGIN:"SUCCESS_LOGIN",
    FAILURE_LOGIN:"FAILURE_LOGIN",
    SET_LOGIN_DATA:"SET_LOGIN_DATA",
    
    SET_USER:"SET_USER",
    REMOVED_USER:"REMOVED_USER",

    SUCCESS_REGISTER:"SUCCESS_REGISTER",
    FAILURE_REGISTER:"FAILURE_REGISTER",
    SET_REGISTER_DATA:"SET_REGISTER_DATA",

    SENT_URL:"SENT_URL",
    SET_VERIFICATION:"SET_VERIFICATION",

    SUCCESS_SET_PROFILE : "SUCCESS_SET_PROFILE",

    SUCCESS_ADD_REQUEST : "SUCCESS_ADD_REQUEST",
    FAILURE_ADD_REQUEST : "FAILURE_ADD_REQUEST",

    SET_ADDRESS_LIST : "SET_ADDRESS_LIST",
    SET_SERVICE_TYPES : "SET_SERVICE_TYPES",
    
    UPDATE_WORK_REQUEST:"UPDATE_WORK_REQUEST",

    SET_PROFILE:"SET_PROFILE",
    SUCCESS_UPDATE_PROFILE:"SUCCESS_UPDATE_PROFILE",

    SUCCESS_UPDATE_SERVICE_STATUS:"SUCCESS_UPDATE_SERVICE_STATUS",
    SUCCESS_GET_SERVICE:"SUCCESS_GET_SERVICE",
    ADD_SERVICE:"ADD_SERVICE",
    GET_SERVICES:"GET_SERVICES",


    
    SET_WORK:"SET_WORK",
    SET_WORKS:"SET_WORKS",
    UPDATE_WORK_STATUS:"UPDATE_WORK_STATUS",
    SUCCESS_UPDATE_WORK_REPORT:"SUCCESS_UPDATE_WORK_REPORT",
   
    SET_OUR_SERVICES:"SET_OUR_SERVICES",
    SET_OUR_SERVICE:"SET_OUR_SERVICE",

    SET_OUR_CUSTOMERS:"SET_OUR_CUSTOMERS",
    SET_OUR_CUSTOMER:"SET_OUR_CUSTOMER",

    SET_OUR_WORKERS:"SET_OUR_WORKERS",
    SET_OUR_WORKER:"SET_OUR_WORKER",


    START_SET_OUR_CUSTOMER:"START_SET_OUR_CUSTOMER",
    SUCCESS_SET_OUR_CUSTOMER:"SUCCESS_SET_OUR_CUSTOMER",
    FAILURE_SET_OUR_CUSTOMER:"FAILURE_SET_OUR_CUSTOMER",


    START_SET_OUR_EMPLOYEE:"START_SET_OUR_EMPLOYEE",
    SUCCESS_SET_OUR_EMPLOYEE:"SUCCESS_SET_OUR_EMPLOYEE",
    FAILURE_SET_OUR_EMPLOYEE:"FAILURE_SET_OUR_EMPLOYEE",


    START_SET_NOTIFICATION:"START_SET_NOTIFICATION",
    SUCCESS_SET_NOTIFICATION:"SUCCESS_SET_NOTIFICATION",
    FAILURE_SET_NOTIFICATION:"FAILURE_SET_NOTIFICATION",


    SET_CONTACT_VERIFICATION:"SET_CONTACT_VERIFICATION",


}